// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsijafnesjkdcnvrkdsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzaWphZm5lc2prZGNudnJrZHNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMDQxMjQsImV4cCI6MjA2MzY4MDEyNH0.zflJk5qSkH1Hsa67jXW63QpEXq0WCUwHvSJXto2gasw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);